ROLE_ADMIN = "NexPort Admin"
ROLE_FINANCE = "NexPort Finance"
ROLE_WAREHOUSE = "NexPort Warehouse"
ROLE_PROCUREMENT = "NexPort Procurement"
ROLE_SALES = "NexPort Sales"

CURRENCIES = ["THB", "USD", "CNY"]
GAP_DEADLINE_DAYS = 30
DEFAULT_MARKUP_MULTIPLIER = 1.0
STOCK_ALERT_THRESHOLD_DAYS = 60
MAX_EXCHANGE_RATE_DEVIATION = 0.05

DEFAULT_FALLBACK_CODE = "GEN"
SETTINGS_DOCTYPE = "NexPort Settings"

